package main

import (
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestLabel(t *testing.T) {
	for _, tc := range []struct {
		name  string
		label string
	}{
		{"backup", "launched.backup"},
		{"My Backup Job", "launched.my_backup_job"},
		{"Some\t whitespace", "launched.some_whitespace"},
		{"keeps.dots-and_underscores", "launched.keeps.dots-and_underscores"},
		// shell metacharacters must not survive into the install script
		{"x`id`", "launched.x_id"},
		{"x$(id)", "launched.x_id"},
		{"x; rm -rf /", "launched.x_rm_-rf"},
		{"x | tee /tmp/x", "launched.x_tee_tmp_x"},
		{"x`{touch,/tmp/pwned}`", "launched.x_touch_tmp_pwned"},
		{"../../etc/passwd", "launched..._.._etc_passwd"},
		{"x\ny", "launched.x_y"},
		{"", "launched.plist"},
		{"!!!", "launched.plist"},
	} {
		assert.Equal(t, tc.label, LaunchdPlist{Name: tc.name}.Label(), "name: %q", tc.name)
	}
}

func TestPlistXMLSourceComment(t *testing.T) {
	p := LaunchdPlist{Name: "backup", Command: "true"}

	xml := p.PlistXML("https://launched.zerowidth.com/plists/abc123")
	assert.Contains(t, xml, "<!-- generated by launched https://launched.zerowidth.com/plists/abc123 -->\n<plist ")
	// a comment ahead of the XML declaration wouldn't be well-formed
	assert.True(t, strings.HasPrefix(xml, `<?xml version="1.0" encoding="UTF-8"?>`), "declaration must come first")

	assert.NotContains(t, p.PlistXML(""), "<!--", "no URL, no comment")
}

func TestPlistURL(t *testing.T) {
	original := baseURL
	defer func() { baseURL = original }()

	baseURL = "https://launched.zerowidth.com"
	assert.Equal(t, "https://launched.zerowidth.com/plists/abc123", plistURL("abc123"))
}
